# Generated by Django 2.2 on 2021-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(None, 'rating'), (1, 'worst'), (2, 'worst'), (3, 'worst'), (4, 'worst'), (5, 'worst')]),
        ),
    ]
