# Generated by Django 2.2 on 2021-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20211222_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(None, 'rating'), (1, 'worst'), (2, 'bad'), (3, 'not good'), (4, 'good'), (5, 'excellent')]),
        ),
    ]
